@startuml

title MovieRater Package Diagram

package "core" {
    component movierater.core
    component movierater.json
}

package "fxui" {
    component movierater.fxui
}

component "jackson" {
}

component "javafx" {
}

component "TestFX" {
}

movierater.fxui ..> javafx
movierater.fxui ..> TestFX
movierater.fxui ..> movierater.core
movierater.fxui ..> movierater.json
movierater.json ..> jackson

@enduml